package utils;

import game.Game;
import game.types.board.SiteType;
import main.Constants;
import other.context.Context;
import other.context.TempContext;
import other.state.container.ContainerState;

/**
 * ContextDeterminiser
 * -------------------
 *
 * Handles determinization for Ludii games with hidden information.
 *
 * In imperfect information games, an agent should not see the opponent's
 * hidden pieces directly. This class replaces the hidden information in a
 * copy of the game context with a plausible hypothesis that is consistent with
 * what the agent already knows (hits and misses for example).
 *
 * This is the Ludii equivalent of _copy(playerId) in TAG.
 *
 * NOTE: The correct hidden type is detected automatically from the .lud file.
 * The hypothesis itself is generated by a DeterminizationEngine (CSP-based),
 * which is currently specific to Battleship. Generalising the engine to
 * other games is left as future work.
 *
 * @author LECHAT Jérôme
 */
public class ContextDeterminiser
{

    /**
     * Hidden information types
     * ------------------------
     *
     * Supported hidden types:
     *   WHO -> the presence of a piece is hidden (e.g. Battleship)
     *   WHAT -> the type/value of a piece is hidden (e.g. Stratego)
     *   WHO_AND_WHAT -> both presence and value are hidden (e.g. Poker)
     */
    public enum HiddenType
    {
        WHO,
        WHAT,
        WHO_AND_WHAT
    }

    /**
     * RAW hidden information type auto detect
     * ---------------------------------------
     *
     * Reads the .lud file of the game and detects automatically the type of hidden information
     *
     * Exemples:
     *   Battleships.lud: (set Hidden (sites P1 ...) to:P2) -> WHO_AND_WHAT
     *   Stratego.lud: (set HiddenWhat (sites P1) to:P2) -> WHAT
     *
     * @param game The loaded game
     * @return The detected HiddenType
     */
    public static HiddenType detect(final Game game)
    {

        // System.out.println("Game: " + game.name());   [DEBUG]
        // System.out.println("numSites: " + game.board().numSites());   [DEBUG]
        // System.out.println("numContainers: " + game.equipment().containers().length);   [DEBUG]
        // System.out.println("numComponents: " + game.numComponents());   [DEBUG]
        /* for (int i = 0; i < game.equipment().containers().length; i++) {
            System.out.println("Container " + i + ": " + game.equipment().containers()[i].name()
                + " -> " + game.equipment().containers()[i].numSites() + " sites");
    }   [DEBUG] */

        final String desc = game.description().raw();

        // System.out.println(desc);   [DEBUG]

        final boolean hasHiddenWho = desc.contains("Hidden Who");
        final boolean hasHiddenWhat = desc.contains("Hidden What");
        final boolean hasHiddenAll = desc.contains("set Hidden (") || desc.contains("set Hidden {") || (desc.contains("set Hidden ") && !hasHiddenWho && !hasHiddenWhat);

        // System.out.print(hasHiddenWho);   [DEBUG]
        // System.out.print(hasHiddenWhat);   [DEBUG]
        // System.out.print(hasHiddenAll);   [DEBUG]

        if (hasHiddenAll) return HiddenType.WHO_AND_WHAT;
        if (hasHiddenWhat && hasHiddenWho) return HiddenType.WHO_AND_WHAT;
        if (hasHiddenWhat) return HiddenType.WHAT;
        if (hasHiddenWho) return HiddenType.WHO;

        return HiddenType.WHO; // Default type game, made for Battleship [THESIS ONLY]
    }

    /**
     * Injection (Battleship ONLY [FOR THE THESIS])
     * ---------------------------
     *
     * Wrapper made for Battleship
     */
    public static Context getDeterminisedContext(final Context context, final int playerID, final DeterminizationEngine engine)
    {
        return getDeterminisedContext(context, playerID, engine, HiddenType.WHO);
    }

    /**
     * Injection (Generical version)
     * -----------------------------
     *
     * Creates a determinized contect by injecting a coherant hypothesis
     * It injects a coherent value in the cases based on the HiddenType
     *
     * @param context The original context (the original game state)
     * @param playerID The active player (Player 1 or Player 2)
     * @param engine The CSP-like engine containing constraints (HIs/MISSes for example)
     * @param hiddenType The type of hidden information that must be injected
     * @return A copy of the context containing a coherant hypothesis
     */
    public static Context getDeterminisedContext(final Context context, final int playerID, final DeterminizationEngine engine, final HiddenType hiddenType)
    {
        // We make a clean copy with TempContext
        final Context copy = new TempContext(context);

        // We generate our hypothesis with our CSP-like Engine (for Battleship only for now)
        final boolean[][] hypothesis = engine.solveCSP(null);

        // We inject via setSite()
        final ContainerState cs = copy.state().containerStates()[0];

        final int opponentZoneStart = (playerID == 1) ? 100 : 0;
        final int opponentID = (playerID == 1) ? 2 : 1;
        final int gridSize = engine.getGridSize();

        for (int x = 0; x < gridSize; x++)
        {
            for (int y = 0; y < gridSize; y++)
            {
                final int site = opponentZoneStart + y * gridSize + x;

                final int whoVal = resolveWho(hiddenType, hypothesis[x][y], opponentID);
                final int whatVal = resolveWhat(hiddenType, hypothesis[x][y], opponentID);

                cs.setSite(
                    copy.state(),
                    site,
                    whoVal,
                    whatVal,
                    Constants.UNDEFINED,
                    Constants.UNDEFINED,
                    Constants.UNDEFINED,
                    Constants.UNDEFINED,
                    SiteType.Cell
                );
            }
        }

        return copy;
    }

    // -------------------------------------------------------------------------
    // Resolvers
    // -------------------------------------------------------------------------

    private static int resolveWho(final HiddenType type, final boolean hasShip, final int opponentID)
    {
        if (type == HiddenType.WHO || type == HiddenType.WHO_AND_WHAT) {
            return hasShip ? opponentID : 0;
        }
        return Constants.UNDEFINED;
    }

    private static int resolveWhat(final HiddenType type, final boolean hasShip, final int opponentID)
    {
        if (type == HiddenType.WHAT || type == HiddenType.WHO_AND_WHAT) {
            return hasShip ? opponentID : Constants.UNDEFINED;
        }
        return Constants.UNDEFINED;
    }
}
